show databases;
USE customer_shopping;
SELECT * FROM customerk LIMIT 10;
SHOW COLUMNS FROM customerk;

alter table customerk
add column month_name varchar(3) as (date_format(purchase_date, '%b'));

## 1. Which are the top 5 products with the highest average review rating?

SELECT item_purchased,
round(avg(review_rating),2) AS "Avg Product Rating"
FROM customerk
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;

## 2. What is the total revenue generated by male vs female customers?

SELECT gender, 
SUM(purchase_amount) AS revenue
FROM customerk
group BY gender;

## 3. What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customerk
GROUP BY age_group
ORDER BY total_revenue DESC;

## 4. Which 5 products have the highest percentage of purchases with discount applied?

SELECT item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_percentage > 0 THEN 1 ELSE 0 END) / COUNT(*),2) AS purchase_with_discount
FROM customerk
GROUP BY item_purchased
ORDER BY purchase_with_discount DESC
LIMIT 5;

## 5. Which 50 customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customerk
WHERE discount_percentage > 0 AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customerk)
LIMIT 50;

## 6. What are the top 3 most purchased products within each category?

WITH item_count AS (
SELECT category, item_purchased, COUNT(customer_id) AS TOTAL_ORDERS, ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id)DESC) AS item_rank
FROM customerk
GROUP BY category, item_purchased)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;

## 7. Do subscribed customers spend more?
-- Compare the average spend and total revenue -- between subscribers and non-subscribers

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customerk
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

## 8. Segment customers into new, returning, loyal based on their -- total number of previous purchases.
-- And show the count of each segment.

WITH customer_type AS( SELECT customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'new'
WHEN previous_purchases BETWEEN  2 AND 10 THEN 'returning'
ELSE 'loyal'
END AS customer_segment FROM customerk)
SELECT customer_segment, COUNT(*) AS 'number of customers'
FROM customer_type
GROUP BY customer_segment;


## 9. Are customers who are reapeated buyers with more than 5 previous purchases also likely to subscribe?

SELECT subscription_status, COUNT(customer_id) AS repeated_buyers 
FROM customerk
WHERE previous_purchases > 5
GROUP BY subscription_status;

## 10. Comapre the average Purchase amount among different payment methods users?

SELECT payment_method,
ROUND(AVG(purchase_amount),2) avg_amount
FROM customerk
WHERE payment_method IN ('Cash on Delivery', 'UPI','Net Banking','Debit Card', 'Credit Card')
GROUP BY payment_method
ORDER BY avg_amount;